openapi: 3.0.3
info:
  title: Api Documentation
  description: Api Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
  version: '1.0'
servers:
  - url: 'http://localhost:7979'
    description: Inferred Url
tags:
  - name: event-controller
    description: Event Controller
paths:
  /events:
    get:
      tags:
        - event-controller
      summary: getAllEvents
      operationId: getAllEventsUsingGET
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
        - event-controller
      summary: createEvent
      operationId: createEventUsingPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '201':
          description: Created
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Event'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/events/{companyName}':
    get:
      tags:
        - event-controller
      summary: findByCompanyName
      operationId: findByCompanyNameUsingGET
      parameters:
        - name: companyName
          in: path
          description: companyName
          required: true
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/{eventId}':
    get:
      tags:
        - event-controller
      summary: getEventById
      operationId: getEventByIdUsingGET
      parameters:
        - name: eventId
          in: path
          description: eventId
          required: true
          style: simple
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Event'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    put:
      tags:
        - event-controller
      summary: updateEvent
      operationId: updateEventUsingPUT
      parameters:
        - name: eventId
          in: path
          description: eventId
          required: true
          style: simple
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    delete:
      tags:
        - event-controller
      summary: deleteEvent
      operationId: deleteEventUsingDELETE
      parameters:
        - name: eventId
          in: path
          description: eventId
          required: true
          style: simple
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
components:
  schemas:
    Event:
      title: Event
      type: object
      properties:
        companyName:
          type: string
        eventId:
          type: integer
          format: int32
        eventName:
          type: string
        location:
          type: string
        mainHost:
          type: string
        moreDetails:
          type: string
        questions:
          type: array
          items:
            type: string
